const countries = [
  {
    name: "Haiti",
    state: [
      {
        name: "Sud",
        cities: [
          "Les Cayes",
          "Aquin",
          "Cavaillon",
          "Saint-Louis-du-Sud",
          "Fond-des-Blancs",
          "Camp-Perrin",
          "Chantal",
          "Île-à-Vache",
          "Maniche",
          "Torbeck",
          "Chardonnières",
          "Les Anglais",
          "Tiburon",
          "Les Côteaux",
          "Port-à-Piment",
          "Roche-à-Bateaux",
          "Port-Salut",
          "Arniquet",
          "Saint-Jean-du-Sud",
        ],
      },
      {
        name: "Artibonite",
        cities: [
          "Dessalines",
          "Desdunes",
          "Grande-Saline",
          "Petite Rivière de l'Artibonite",
          "Gonaïves",
          "Ennery",
          "L'Estère",
          "Gros-Morne",
          "Anse-Rouge",
          "Terre-Neuve",
          "Marmelade",
          "Saint-Michel-de-l'Atalaye",
          "Saint-Marc",
          "Les Arcadins",
          "La Chapelle",
          "Liancourt",
          "Verrettes",
          "Montrouis",
        ],
      },
      {
        name: "Centre",
        cities: [
          "Cerca-la-Source",
          "Thomassique",
          "Hinche",
          "Cerca-Carvajal",
          "Maïssade",
          "Thomonde",
          "Lascahobas",
          "Baptiste",
          "Belladère",
          "Savanette",
          "Mirebalais",
          "Boucan-Carré",
          "Saut-d'Eau",
        ],
      },
      {
        name: "Grand'Anse",
        cities: [
          "Anse-d'Hainault",
          "Dame-Marie",
          "Les Irois",
          "Beaumont",
          "Corail",
          "Pestel",
          "Roseaux",
          "Jérémie",
          "Abricots",
          "Bonbon",
          "Chambellan",
          "Marfranc",
          "Moron",
        ],
      },
      {
        name: "Nippes",
        cities: [
          "Anse-à-Veau",
          "Arnaud",
          "L'Asile",
          "Petit-Trou-de-Nippes",
          "Plaisance-du-Sud",
          "Baradères",
          "Grand-Boucan",
          "Miragoâne",
          "Fonds-des-Nègres",
          "Paillant",
          "Petite-Rivière-de-Nippes",
        ],
      },
      {
        name: "Nord",
        cities: [
          "Acul-du-Nord",
          "Milot",
          "Plaine-du-Nord",
          "Borgne",
          "Port-Margot",
          "Cap-Haïtien",
          "Limonade",
          "Quartier-Morin",
          "Grande-Rivière-du-Nord",
          "Bahon",
          "Limbé",
          "Bas-Limbé",
          "Plaisance",
          "Pilate",
          "Saint-Raphaël",
          "Dondon",
          "La Victoire",
          "Pignon",
          "Ranquitte",
        ],
      },
      {
        name: "Nord-Est",
        cities: [
          "Fort-Liberté",
          "Perches",
          "Ferrier",
          "Ouanaminthe",
          "Capotille",
          "Mont-Organisé",
          "Trou-du-Nord",
          "Caracol",
          "Sainte-Suzanne",
          "Grand-Bassin",
          "Terrier-Rouge",
          "Vallières",
        ],
      },
      {
        name: "Nord-Ouest",
        cities: [
          "Môle-Saint-Nicolas",
          "Baie-de-Henne",
          "Bombardopolis",
          "Jean-Rabel",
          "Port-de-Paix",
          "Bassin-Bleu",
          "Chansolme",
          "Lapointe",
          "La Tortue",
          "Saint-Louis-du-Nord",
          "Anse-à-Foleur",
        ],
      },
      {
        name: "Ouest",
        cities: [
          "Arcahaie",
          "Cabaret",
          "Croix-des-Bouquets",
          "Cornillon",
          "Fonds-Verrettes",
          "Ganthier",
          "Thomazeau",
          "Anse-à-Galets",
          "Pointe-à-Raquette",
          "Léogâne",
          "Grand-Goâve",
          "Petit-Goâve",
          "Port-au-Prince",
          "Carrefour",
          "Cité Soleil",
          "Delmas",
          "Gressier",
          "Kenscoff",
          "Pétion-Ville",
          "Tabarre",
        ],
      },
      {
        name: "Sud-Est",
        cities: [
          "Bainet",
          "Côtes-de-Fer",
          "Belle-Anse",
          "Anse-à-Pitres",
          "Grand-Gosier",
          "Thiotte",
          "Jacmel",
          "Cayes-Jacmel",
          "La Vallée-de-Jacmel",
          "Marigot",
        ],
      },
    ],
  },
  {
    name: "France",
    state: [
      { name: "Auvergne-Rhône-Alpes", cities: ["Lyon", "Grenoble", "Saint-Étienne", "Clermont-Ferrand", "Annecy", "Chambéry", "Valence", "Bourg-en-Bresse"] },
      { name: "Bourgogne-Franche-Comté", cities: ["Dijon", "Besançon", "Auxerre", "Chalon-sur-Saône", "Belfort", "Montbéliard", "Mâcon"] },
      { name: "Bretagne", cities: ["Rennes", "Brest", "Quimper", "Lorient", "Vannes", "Saint-Malo", "Saint-Brieuc"] },
      { name: "Centre-Val de Loire", cities: ["Tours", "Orléans", "Bourges", "Blois", "Chartres", "Châteauroux"] },
      { name: "Corse", cities: ["Ajaccio", "Bastia", "Porto-Vecchio", "Corte", "Propriano"] },
      { name: "Grand Est", cities: ["Strasbourg", "Reims", "Metz", "Nancy", "Mulhouse", "Colmar", "Troyes", "Charleville-Mézières"] },
      { name: "Hauts-de-France", cities: ["Lille", "Amiens", "Roubaix", "Tourcoing", "Dunkerque", "Calais", "Valenciennes", "Arras"] },
      { name: "Île-de-France", cities: ["Paris", "Versailles", "Saint-Denis", "Boulogne-Billancourt", "Montreuil", "Créteil", "Nanterre", "Argenteuil"] },
      { name: "Normandie", cities: ["Rouen", "Caen", "Le Havre", "Cherbourg-en-Cotentin", "Évreux", "Alençon", "Dieppe"] },
      { name: "Nouvelle-Aquitaine", cities: ["Bordeaux", "Limoges", "Pau", "Poitiers", "La Rochelle", "Bayonne", "Périgueux", "Niort"] },
      { name: "Occitanie", cities: ["Toulouse", "Montpellier", "Nîmes", "Perpignan", "Béziers", "Narbonne", "Carcassonne", "Albi", "Tarbes"] },
      { name: "Pays de la Loire", cities: ["Nantes", "Le Mans", "Angers", "Saint-Nazaire", "La Roche-sur-Yon", "Laval"] },
      { name: "Provence-Alpes-Côte d'Azur", cities: ["Marseille", "Nice", "Toulon", "Aix-en-Provence", "Avignon", "Cannes", "Antibes", "Arles"] },
      { name: "La Réunion", cities: ["Saint-Denis", "Saint-Paul", "Saint-Pierre", "Le Tampon", "Saint-André", "Saint-Benoît"] },
      { name: "Mayotte", cities: ["Mamoudzou", "Koungou", "Bandraboua", "Dzaoudzi", "Bouéni"] },
    ],
  },
  {
    name: "Canada",
    state: [
      { name: "Alberta", cities: ["Calgary", "Edmonton", "Red Deer", "Lethbridge", "Medicine Hat", "Grande Prairie", "Airdrie"] },
      { name: "Colombie-Britannique", cities: ["Vancouver", "Victoria", "Kelowna", "Abbotsford", "Surrey", "Burnaby", "Richmond", "Prince George", "Kamloops"] },
      { name: "Manitoba", cities: ["Winnipeg", "Brandon", "Steinbach", "Thompson", "Portage la Prairie"] },
      { name: "Nouveau-Brunswick", cities: ["Fredericton", "Moncton", "Saint John", "Dieppe", "Miramichi", "Edmundston"] },
      { name: "Terre-Neuve-et-Labrador", cities: ["Saint-Jean", "Corner Brook", "Gander", "Paradise", "Mount Pearl", "Labrador City"] },
      { name: "Nouvelle-Écosse", cities: ["Halifax", "Sydney", "Truro", "New Glasgow", "Dartmouth", "Glace Bay"] },
      { name: "Ontario", cities: ["Toronto", "Ottawa", "Mississauga", "Brampton", "Hamilton", "London", "Markham", "Vaughan", "Kingston", "Windsor"] },
      { name: "Île-du-Prince-Édouard", cities: ["Charlottetown", "Summerside", "Stratford", "Cornwall"] },
      { name: "Québec", cities: ["Montréal", "Québec", "Laval", "Gatineau", "Longueuil", "Sherbrooke", "Saguenay", "Lévis", "Trois-Rivières"] },
      { name: "Saskatchewan", cities: ["Saskatoon", "Regina", "Prince Albert", "Moose Jaw", "Yorkton", "Swift Current"] },
      { name: "Territoires du Nord-Ouest", cities: ["Yellowknife", "Hay River", "Inuvik", "Fort Smith"] },
      { name: "Nunavut", cities: ["Iqaluit", "Rankin Inlet", "Arviat", "Baker Lake"] },
      { name: "Yukon", cities: ["Whitehorse", "Dawson City", "Watson Lake", "Haines Junction"] },
    ],
  },
  {
    name: "République Dominicaine",
    state: [
      { name: "Azua", cities: ["Azua de Compostela", "Las Charcas", "Las Yayas de Viajama", "Padre Las Casas"] },
      { name: "Bahoruco", cities: ["Neyba", "Galván", "Los Ríos", "Tamayo"] },
      { name: "Barahona", cities: ["Barahona", "Cabral", "Enriquillo", "Jaquimeyes"] },
      { name: "Dajabón", cities: ["Dajabón", "Loma de Cabrera", "Partido", "Restauración"] },
      { name: "Distrito Nacional", cities: ["Santo Domingo"] },
      { name: "Duarte", cities: ["San Francisco de Macorís", "Castillo", "Las Guáranas", "Villa Riva"] },
      { name: "El Seibo", cities: ["El Seibo", "Miches"] },
      { name: "Elías Piña", cities: ["Comendador", "El Llano", "Hondo Valle", "Pedro Santana"] },
      { name: "Espaillat", cities: ["Moca", "Gaspar Hernández", "Jamao al Norte"] },
      { name: "Hato Mayor", cities: ["Hato Mayor del Rey", "El Valle", "Sabana de la Mar"] },
      { name: "Hermanas Mirabal", cities: ["Salcedo", "Tenares", "Villa Tapia"] },
      { name: "Independencia", cities: ["Jimaní", "Duvergé", "La Descubierta", "Postrer Río"] },
      { name: "La Altagracia", cities: ["Higüey", "San Rafael del Yuma", "Bávaro", "Punta Cana"] },
      { name: "La Romana", cities: ["La Romana", "Caleta", "Villa Hermosa"] },
      { name: "La Vega", cities: ["Concepción de La Vega", "Constanza", "Jarabacoa", "Jima Abajo"] },
      { name: "María Trinidad Sánchez", cities: ["Nagua", "El Factor", "Río San Juan"] },
      { name: "Monseñor Nouel", cities: ["Bonao", "Maimón", "Piedra Blanca"] },
      { name: "Monte Cristi", cities: ["Monte Cristi", "Guayubín", "Las Matas de Santa Cruz", "Pepillo Salcedo"] },
      { name: "Monte Plata", cities: ["Monte Plata", "Bayaguana", "Sabana Grande de Boyá"] },
      { name: "Pedernales", cities: ["Pedernales", "Oviedo"] },
      { name: "Peravia", cities: ["Baní", "Nizao", "Matanzas"] },
      { name: "Puerto Plata", cities: ["Puerto Plata", "Sosúa", "Cabarete", "Luperón", "Imbert"] },
      { name: "Samaná", cities: ["Santa Bárbara de Samaná", "Las Terrenas", "El Limón", "Sánchez"] },
      { name: "San Cristóbal", cities: ["San Cristóbal", "Bajos de Haina", "Villa Altagracia", "Cambita Garabitos"] },
      { name: "San José de Ocoa", cities: ["San José de Ocoa", "Sabana Larga"] },
      { name: "San Juan", cities: ["San Juan de la Maguana", "Las Matas de Farfán", "Vallejuelo", "El Cercado"] },
      { name: "San Pedro de Macorís", cities: ["San Pedro de Macorís", "Guayacanes", "Juan Dolio", "Ramón Santana"] },
      { name: "Sánchez Ramírez", cities: ["Cotuí", "Cevicos", "Fantino"] },
      { name: "Santiago", cities: ["Santiago de los Caballeros", "Tamboril", "Villa González", "Licey al Medio", "Jánico"] },
      { name: "Santiago Rodríguez", cities: ["Sabaneta", "Monción", "Los Almácigos"] },
      { name: "Santo Domingo", cities: ["Santo Domingo Este", "Santo Domingo Norte", "Santo Domingo Oeste", "Boca Chica"] },
      { name: "Valverde", cities: ["Mao", "Esperanza", "Laguna Salada"] },
    ],
  },
  {
    name: "Brésil",
    state: [
      { name: "Acre", cities: ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira", "Tarauacá"] },
      { name: "Alagoas", cities: ["Maceió", "Arapiraca", "Palmeira dos Índios", "União dos Palmares"] },
      { name: "Amapá", cities: ["Macapá", "Santana", "Laranjal do Jari", "Oiapoque"] },
      { name: "Amazonas", cities: ["Manaus", "Parintins", "Itacoatiara", "Manacapuru", "Tefé"] },
      { name: "Bahia", cities: ["Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari", "Ilhéus", "Juazeiro"] },
      { name: "Ceará", cities: ["Fortaleza", "Caucaia", "Juazeiro do Norte", "Sobral", "Crato"] },
      { name: "Distrito Federal", cities: ["Brasília", "Taguatinga", "Ceilândia", "Samambaia"] },
      { name: "Espírito Santo", cities: ["Vitória", "Vila Velha", "Cariacica", "Serra", "Cachoeiro de Itapemirim"] },
      { name: "Goiás", cities: ["Goiânia", "Aparecida de Goiânia", "Anápolis", "Rio Verde", "Luziânia"] },
      { name: "Maranhão", cities: ["São Luís", "Imperatriz", "Timon", "Caxias", "Codó"] },
      { name: "Mato Grosso", cities: ["Cuiabá", "Várzea Grande", "Rondonópolis", "Sinop", "Tangará da Serra"] },
      { name: "Mato Grosso do Sul", cities: ["Campo Grande", "Dourados", "Três Lagoas", "Corumbá"] },
      { name: "Minas Gerais", cities: ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora", "Betim", "Montes Claros"] },
      { name: "Pará", cities: ["Belém", "Ananindeua", "Santarém", "Marabá", "Castanhal"] },
      { name: "Paraíba", cities: ["João Pessoa", "Campina Grande", "Santa Rita", "Patos"] },
      { name: "Paraná", cities: ["Curitiba", "Londrina", "Maringá", "Ponta Grossa", "Cascavel", "Foz do Iguaçu"] },
      { name: "Pernambuco", cities: ["Recife", "Caruaru", "Olinda", "Petrolina", "Jaboatão dos Guararapes", "Paulista"] },
      { name: "Piauí", cities: ["Teresina", "Parnaíba", "Picos", "Floriano"] },
      { name: "Rio de Janeiro", cities: ["Rio de Janeiro", "São Gonçalo", "Duque de Caxias", "Nova Iguaçu", "Niterói", "Belford Roxo"] },
      { name: "Rio Grande do Norte", cities: ["Natal", "Mossoró", "Parnamirim", "Caicó"] },
      { name: "Rio Grande do Sul", cities: ["Porto Alegre", "Caxias do Sul", "Pelotas", "Canoas", "Santa Maria"] },
      { name: "Rondônia", cities: ["Porto Velho", "Ji-Paraná", "Ariquemes", "Cacoal"] },
      { name: "Roraima", cities: ["Boa Vista", "Rorainópolis", "Caracaraí"] },
      { name: "Santa Catarina", cities: ["Florianópolis", "Joinville", "Blumenau", "São José", "Criciúma", "Chapecó"] },
      { name: "São Paulo", cities: ["São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo", "Santo André", "Osasco", "Sorocaba", "Ribeirão Preto"] },
      { name: "Sergipe", cities: ["Aracaju", "Nossa Senhora do Socorro", "Lagarto", "Itabaiana"] },
      { name: "Tocantins", cities: ["Palmas", "Araguaína", "Gurupi", "Porto Nacional"] },
    ],
  },
  {
    name: "Chili",
    state: [
      { name: "Arica y Parinacota", cities: ["Arica", "Putre"] },
      { name: "Tarapacá", cities: ["Iquique", "Alto Hospicio"] },
      { name: "Antofagasta", cities: ["Antofagasta", "Calama", "Tocopilla", "Mejillones"] },
      { name: "Atacama", cities: ["Copiapó", "Vallenar", "Caldera", "Chañaral"] },
      { name: "Coquimbo", cities: ["La Serena", "Coquimbo", "Ovalle", "Illapel"] },
      { name: "Valparaíso", cities: ["Valparaíso", "Viña del Mar", "Quilpué", "Villa Alemana", "San Antonio", "Los Andes"] },
      { name: "Metropolitana de Santiago", cities: ["Santiago", "Puente Alto", "Maipú", "La Florida", "Las Condes", "Providencia", "Ñuñoa"] },
      { name: "O'Higgins", cities: ["Rancagua", "San Fernando", "Machalí", "Pichilemu"] },
      { name: "Maule", cities: ["Talca", "Curicó", "Linares", "Constitución"] },
      { name: "Ñuble", cities: ["Chillán", "San Carlos", "Bulnes", "Yungay"] },
      { name: "Biobío", cities: ["Concepción", "Talcahuano", "Los Ángeles", "Coronel", "Hualpén"] },
      { name: "La Araucanía", cities: ["Temuco", "Padre Las Casas", "Villarrica", "Pucón"] },
      { name: "Los Ríos", cities: ["Valdivia", "La Unión", "Panguipulli"] },
      { name: "Los Lagos", cities: ["Puerto Montt", "Osorno", "Castro", "Puerto Varas", "Ancud"] },
      { name: "Aysén", cities: ["Coyhaique", "Aysén", "Chile Chico", "Puerto Cisnes"] },
      { name: "Magallanes y la Antártica Chilena", cities: ["Punta Arenas", "Puerto Natales", "Porvenir"] },
    ],
  },
  {
    name: "Jamaïque",
    state: [
      { name: "Clarendon", cities: ["May Pen", "Chapelton", "Lionel Town", "Rock River"] },
      { name: "Hanover", cities: ["Lucea", "Sandy Bay", "Hopewell", "Green Island"] },
      { name: "Kingston", cities: ["Kingston", "Port Royal", "Harbour View"] },
      { name: "Manchester", cities: ["Mandeville", "Christiana", "Newport", "Porus"] },
      { name: "Portland", cities: ["Port Antonio", "Buff Bay", "Hope Bay", "Manchioneal"] },
      { name: "Saint Andrew", cities: ["Half Way Tree", "Stony Hill", "Papine", "Constant Spring"] },
      { name: "Saint Ann", cities: ["Saint Ann's Bay", "Ocho Rios", "Runaway Bay", "Brown's Town"] },
      { name: "Saint Catherine", cities: ["Spanish Town", "Portmore", "Old Harbour", "Linstead"] },
      { name: "Saint Elizabeth", cities: ["Black River", "Treasure Beach", "Junction", "Santa Cruz"] },
      { name: "Saint James", cities: ["Montego Bay", "Ironshore", "Rose Hall", "Anchovy"] },
      { name: "Saint Mary", cities: ["Port Maria", "Annotto Bay", "Highgate", "Oracabessa"] },
      { name: "Saint Thomas", cities: ["Morant Bay", "Yallahs", "Port Morant", "Bath"] },
      { name: "Trelawny", cities: ["Falmouth", "Duncans", "Wakefield", "Clark's Town"] },
      { name: "Westmoreland", cities: ["Savanna-la-Mar", "Negril", "Whithorn", "Petersfield"] },
    ],
  },
  {
    name: "Cuba",
    state: [
      { name: "Artemisa", cities: ["Artemisa", "Güira de Melena", "San Antonio de los Baños", "Bejucal"] },
      { name: "Camagüey", cities: ["Camagüey", "Nuevitas", "Florida", "Guáimaro"] },
      { name: "Ciego de Ávila", cities: ["Ciego de Ávila", "Morón", "Bolivia", "Baraguá"] },
      { name: "Cienfuegos", cities: ["Cienfuegos", "Palmira", "Cruces", "Cumanayagua"] },
      { name: "Granma", cities: ["Bayamo", "Manzanillo", "Guisa", "Jiguaní"] },
      { name: "Guantánamo", cities: ["Guantánamo", "Baracoa", "Imías", "Maisí"] },
      { name: "Holguín", cities: ["Holguín", "Banes", "Moa", "Gibara", "Mayarí"] },
      { name: "La Habana", cities: ["La Habana", "Boyeros", "Playa", "Centro Habana", "Habana del Este"] },
      { name: "Las Tunas", cities: ["Las Tunas", "Puerto Padre", "Manatí", "Amancio"] },
      { name: "Matanzas", cities: ["Matanzas", "Varadero", "Cárdenas", "Colón"] },
      { name: "Mayabeque", cities: ["Güines", "Bejucal", "San José de las Lajas", "Madruga"] },
      { name: "Pinar del Río", cities: ["Pinar del Río", "Consolación del Sur", "Guane", "Viñales"] },
      { name: "Sancti Spíritus", cities: ["Sancti Spíritus", "Trinidad", "Cabaiguán", "Fomento"] },
      { name: "Santiago de Cuba", cities: ["Santiago de Cuba", "San Luis", "Palma Soriano", "Contramaestre"] },
      { name: "Villa Clara", cities: ["Santa Clara", "Caibarién", "Sagua la Grande", "Placetas"] },
      { name: "Isla de la Juventud", cities: ["Nueva Gerona", "La Demajagua"] },
    ],
  },
  {
    name: "Mexique",
    state: [
      { name: "Aguascalientes", cities: ["Aguascalientes", "Jesús María", "Calvillo", "San Francisco de los Romo"] },
      { name: "Baja California", cities: ["Tijuana", "Mexicali", "Ensenada", "Tecate", "Rosarito"] },
      { name: "Baja California Sur", cities: ["La Paz", "Los Cabos", "Loreto", "Comondú"] },
      { name: "Campeche", cities: ["Campeche", "Ciudad del Carmen", "Champotón"] },
      { name: "Chiapas", cities: ["Tuxtla Gutiérrez", "San Cristóbal de las Casas", "Tapachula", "Comitán"] },
      { name: "Chihuahua", cities: ["Chihuahua", "Ciudad Juárez", "Delicias", "Hidalgo del Parral", "Cuauhtémoc"] },
      { name: "Ciudad de México", cities: ["Ciudad de México", "Iztapalapa", "Gustavo A. Madero", "Coyoacán", "Tlalpan", "Xochimilco"] },
      { name: "Coahuila", cities: ["Saltillo", "Torreón", "Monclova", "Piedras Negras", "Acuña"] },
      { name: "Colima", cities: ["Colima", "Manzanillo", "Tecomán", "Villa de Álvarez"] },
      { name: "Durango", cities: ["Durango", "Gómez Palacio", "Lerdo", "Santiago Papasquiaro"] },
      { name: "Estado de México", cities: ["Ecatepec", "Toluca", "Naucalpan", "Nezahualcóyotl", "Chimalhuacán", "Texcoco"] },
      { name: "Guanajuato", cities: ["Guanajuato", "León", "Irapuato", "Celaya", "Salamanca"] },
      { name: "Guerrero", cities: ["Chilpancingo", "Acapulco", "Iguala", "Zihuatanejo", "Taxco"] },
      { name: "Hidalgo", cities: ["Pachuca", "Tulancingo", "Tula de Allende", "Actopan"] },
      { name: "Jalisco", cities: ["Guadalajara", "Zapopan", "Tlaquepaque", "Puerto Vallarta", "Tlajomulco de Zúñiga"] },
      { name: "Michoacán", cities: ["Morelia", "Uruapan", "Zamora", "Lázaro Cárdenas", "Apatzingán"] },
      { name: "Morelos", cities: ["Cuernavaca", "Jiutepec", "Cuautla", "Temixco"] },
      { name: "Nayarit", cities: ["Tepic", "Bahía de Banderas", "Xalisco", "Santiago Ixcuintla"] },
      { name: "Nuevo León", cities: ["Monterrey", "Guadalupe", "San Nicolás de los Garza", "Apodaca", "Santa Catarina"] },
      { name: "Oaxaca", cities: ["Oaxaca de Juárez", "Salina Cruz", "Juchitán", "Santa Lucía del Camino"] },
      { name: "Puebla", cities: ["Puebla", "Tehuacán", "San Andrés Cholula", "Cuautlancingo"] },
      { name: "Querétaro", cities: ["Santiago de Querétaro", "San Juan del Río", "El Marqués", "Corregidora"] },
      { name: "Quintana Roo", cities: ["Cancún", "Playa del Carmen", "Chetumal", "Tulum", "Isla Mujeres"] },
      { name: "San Luis Potosí", cities: ["San Luis Potosí", "Soledad de Graciano Sánchez", "Ciudad Valles", "Matehuala"] },
      { name: "Sinaloa", cities: ["Culiacán", "Mazatlán", "Los Mochis", "Guasave"] },
      { name: "Sonora", cities: ["Hermosillo", "Ciudad Obregón", "Nogales", "San Luis Río Colorado"] },
      { name: "Tabasco", cities: ["Villahermosa", "Comalcalco", "Cárdenas", "Macuspana"] },
      { name: "Tamaulipas", cities: ["Reynosa", "Matamoros", "Nuevo Laredo", "Ciudad Victoria", "Tampico"] },
      { name: "Tlaxcala", cities: ["Tlaxcala", "Apizaco", "Huamantla", "Calpulalpan"] },
      { name: "Veracruz", cities: ["Veracruz", "Xalapa", "Coatzacoalcos", "Orizaba", "Poza Rica"] },
      { name: "Yucatán", cities: ["Mérida", "Valladolid", "Progreso", "Ticul"] },
      { name: "Zacatecas", cities: ["Zacatecas", "Fresnillo", "Guadalupe", "Jerez"] },
    ],
  },
  {
    name: "Bahamas",
    state: [
      { name: "New Providence", cities: ["Nassau", "Cable Beach", "Paradise Island", "Lyford Cay"] },
      { name: "Grand Bahama", cities: ["Freeport", "Lucaya", "West End", "Eight Mile Rock"] },
      { name: "Abaco", cities: ["Marsh Harbour", "Green Turtle Cay", "Hope Town", "Treasure Cay"] },
      { name: "Andros", cities: ["Nicholl's Town", "Mangrove Cay", "Congo Town", "Fresh Creek"] },
      { name: "Berry Islands", cities: ["Great Harbour Cay", "Bullocks Harbour"] },
      { name: "Bimini", cities: ["Alice Town", "Bailey Town", "Porgy Bay"] },
      { name: "Cat Island", cities: ["Arthur's Town", "Old Bight", "New Bight"] },
      { name: "Crooked Island & Acklins", cities: ["Colonel Hill", "Spring Point", "Pinefield"] },
      { name: "Eleuthera", cities: ["Rock Sound", "Governor's Harbour", "Spanish Wells", "Harbour Island"] },
      { name: "Exuma", cities: ["George Town", "Staniel Cay", "Barraterre"] },
      { name: "Inagua", cities: ["Matthew Town"] },
      { name: "Long Island", cities: ["Clarence Town", "Deadman's Cay", "Stella Maris"] },
      { name: "Mayaguana", cities: ["Abraham's Bay", "Betsy Bay"] },
      { name: "Ragged Island", cities: ["Duncan Town"] },
      { name: "San Salvador", cities: ["Cockburn Town", "Victoria Hill"] },
    ],
  },
  {
    name: "Guyane française",
    state: [
      { name: "Cayenne", cities: ["Cayenne", "Matoury", "Rémire-Montjoly", "Montsinéry-Tonnegrande"] },
      { name: "Centre Littoral", cities: ["Kourou", "Sinnamary", "Iracoubo"] },
      { name: "Ouest Guyanais", cities: ["Saint-Laurent-du-Maroni", "Mana", "Apatou", "Grand-Santi", "Papaïchton"] },
      { name: "Est Guyanais", cities: ["Saint-Georges", "Ouanary", "Camopi", "Régina"] },
      { name: "Haut Maroni", cities: ["Maripasoula", "Saül"] },
      { name: "Sud", cities: ["Roura", "Cacao"] },
    ],
  },
  {
    name: "Guyana",
    state: [
      { name: "Barima-Waini", cities: ["Mabaruma", "Port Kaituma", "Kumaka"] },
      { name: "Pomeroon-Supenaam", cities: ["Anna Regina", "Supenaam", "Charity"] },
      { name: "Essequibo Islands-West Demerara", cities: ["Vreed-en-Hoop", "Leonora", "Parika"] },
      { name: "Demerara-Mahaica", cities: ["Georgetown", "Timehri", "Mahaica", "Buxton"] },
      { name: "Mahaica-Berbice", cities: ["Fort Wellington", "Rosignol", "Mahaicony"] },
      { name: "East Berbice-Corentyne", cities: ["New Amsterdam", "Corriverton", "Skeldon", "Rose Hall"] },
      { name: "Cuyuni-Mazaruni", cities: ["Bartica", "Issano", "Imbaimadai"] },
      { name: "Potaro-Siparuni", cities: ["Mahdia", "Paramakatoi", "Tumatumari"] },
      { name: "Upper Takutu-Upper Essequibo", cities: ["Lethem", "Annai", "Aishalton"] },
      { name: "Upper Demerara-Berbice", cities: ["Linden", "Kwakwani", "Ituni"] },
    ],
  },
  {
    name: "Venezuela",
    state: [
      { name: "Amazonas", cities: ["Puerto Ayacucho", "San Fernando de Atabapo", "La Esmeralda"] },
      { name: "Anzoátegui", cities: ["Barcelona", "Puerto La Cruz", "El Tigre", "Anaco", "Lecherías"] },
      { name: "Apure", cities: ["San Fernando de Apure", "Guasdualito", "Achaguas"] },
      { name: "Aragua", cities: ["Maracay", "La Victoria", "Turmero", "Cagua", "Villa de Cura"] },
      { name: "Barinas", cities: ["Barinas", "Barinitas", "Socopó", "Santa Bárbara"] },
      { name: "Bolívar", cities: ["Ciudad Bolívar", "Ciudad Guayana", "Upata", "Caicara del Orinoco"] },
      { name: "Carabobo", cities: ["Valencia", "Guacara", "Los Guayos", "Naguanagua", "San Diego"] },
      { name: "Cojedes", cities: ["San Carlos", "Tinaco", "El Baúl"] },
      { name: "Delta Amacuro", cities: ["Tucupita", "Barrancas del Orinoco", "Pedernales"] },
      { name: "Distrito Capital", cities: ["Caracas", "Petare", "El Paraíso"] },
      { name: "Falcón", cities: ["Coro", "Punto Fijo", "La Vela de Coro", "Tucacas"] },
      { name: "Guárico", cities: ["San Juan de los Morros", "Valle de La Pascua", "Calabozo"] },
      { name: "Lara", cities: ["Barquisimeto", "Cabudare", "Carora", "El Tocuyo"] },
      { name: "Mérida", cities: ["Mérida", "El Vigía", "Ejido", "Tovar"] },
      { name: "Miranda", cities: ["Los Teques", "Guarenas", "Guatire", "Charallave", "Ocumare del Tuy"] },
      { name: "Monagas", cities: ["Maturín", "Caripito", "Punta de Mata", "Temblador"] },
      { name: "Nueva Esparta", cities: ["La Asunción", "Porlamar", "Pampatar", "Juangriego"] },
      { name: "Portuguesa", cities: ["Guanare", "Acarigua", "Araure", "Biscucuy"] },
      { name: "Sucre", cities: ["Cumaná", "Carúpano", "Güiria", "Cariaco"] },
      { name: "Táchira", cities: ["San Cristóbal", "Táriba", "Rubio", "La Fría"] },
      { name: "Trujillo", cities: ["Trujillo", "Valera", "Boconó", "Pampán"] },
      { name: "Vargas", cities: ["La Guaira", "Catia La Mar", "Maiquetía", "Naiguatá"] },
      { name: "Yaracuy", cities: ["San Felipe", "Yaritagua", "Nirgua", "Chivacoa"] },
      { name: "Zulia", cities: ["Maracaibo", "Cabimas", "Ciudad Ojeda", "San Francisco"] },
    ],
  },
  {
    name: "Anguilla",
    state: [
      { name: "Main Island", cities: ["The Valley", "Sandy Ground", "Blowing Point", "West End", "Island Harbour", "South Hill", "Stoney Ground"] },
    ],
  },
  {
    name: "Antigua-et-Barbuda",
    state: [
      { name: "Saint George", cities: ["St John's"] },
      { name: "Saint John", cities: ["Saint John's", "Piggotts", "Grays Farm"] },
      { name: "Saint Mary", cities: ["Bolans", "Old Road"] },
      { name: "Saint Paul", cities: ["English Harbour", "Falmouth", "Liberta"] },
      { name: "Saint Peter", cities: ["Parham", "Pares"] },
      { name: "Saint Philip", cities: ["Freetown", "All Saints"] },
      { name: "Barbuda", cities: ["Codrington"] },
    ],
  },
  {
    name: "Aruba",
    state: [
      { name: "Main Island", cities: ["Oranjestad", "San Nicolas", "Noord", "Santa Cruz", "Savaneta", "Paradera"] },
    ],
  },
  {
    name: "Barbade",
    state: [
      { name: "Christ Church", cities: ["Oistins", "Worthing", "Welches", "Hastings"] },
      { name: "Saint Andrew", cities: ["Belleplaine", "Cattlewash"] },
      { name: "Saint George", cities: ["Flatfield", "Constant"] },
      { name: "Saint James", cities: ["Holetown", "Speightstown", "Sunset Crest"] },
      { name: "Saint John", cities: ["Bathsheba", "Consett"] },
      { name: "Saint Joseph", cities: ["Sharon", "Bathsheba"] },
      { name: "Saint Lucy", cities: ["Speightstown", "Spring Hall"] },
      { name: "Saint Michael", cities: ["Bridgetown", "Black Rock", "Wildey", "Bayville"] },
      { name: "Saint Peter", cities: ["Speightstown", "Six Men's Bay"] },
      { name: "Saint Philip", cities: ["Six Cross Roads", "Crane", "Sunbury"] },
      { name: "Saint Thomas", cities: ["Edgecliff", "Welchman Hall"] },
    ],
  },
  {
    name: "Belize",
    state: [
      { name: "Belize", cities: ["Belize City", "Ladyville", "Hattieville", "Burrell Boom"] },
      { name: "Cayo", cities: ["San Ignacio", "Belmopan", "Santa Elena", "Benque Viejo del Carmen"] },
      { name: "Corozal", cities: ["Corozal Town", "Consejo", "Ranchito"] },
      { name: "Orange Walk", cities: ["Orange Walk Town", "Sarteneja", "San Estevan"] },
      { name: "Stann Creek", cities: ["Dangriga", "Placencia", "Hopkins", "Seine Bight"] },
      { name: "Toledo", cities: ["Punta Gorda", "San Antonio", "San Pedro Columbia"] },
    ],
  },
  {
    name: "Îles Vierges britanniques",
    state: [
      { name: "Tortola", cities: ["Road Town", "Long Look", "West End", "East End"] },
      { name: "Virgin Gorda", cities: ["Spanish Town", "North Sound"] },
      { name: "Anegada", cities: ["The Settlement"] },
      { name: "Jost Van Dyke", cities: ["Great Harbour", "White Bay"] },
    ],
  },
  {
    name: "Îles Caïmans",
    state: [
      { name: "Grand Cayman", cities: ["George Town", "West Bay", "Bodden Town", "East End", "North Side"] },
      { name: "Cayman Brac", cities: ["Stake Bay", "West End", "Tibbetts Turn"] },
      { name: "Little Cayman", cities: ["Blossom Village"] },
    ],
  },
  {
    name: "Curaçao",
    state: [
      { name: "Main Island", cities: ["Willemstad", "Punda", "Otrobanda", "Barber", "Westpunt", "Sint Michiel"] },
    ],
  },
  {
    name: "Dominique",
    state: [
      { name: "Saint Andrew", cities: ["Marigot", "Wesley", "Woodford Hill"] },
      { name: "Saint David", cities: ["Grand Bay", "La Plaine"] },
      { name: "Saint George", cities: ["Roseau", "Canefield", "Bath Estate"] },
      { name: "Saint John", cities: ["Portsmouth", "Glanvillia"] },
      { name: "Saint Joseph", cities: ["Salisbury", "Mero", "Layou"] },
      { name: "Saint Luke", cities: ["Soufrière"] },
      { name: "Saint Mark", cities: ["Coulibistrie", "Dublanc"] },
      { name: "Saint Patrick", cities: ["Berekua", "Pointe Michel"] },
      { name: "Saint Paul", cities: ["Mahaut", "Massacre"] },
      { name: "Saint Peter", cities: ["Colihaut", "Bioche"] },
    ],
  },
  {
    name: "Grenade",
    state: [
      { name: "Saint Andrew", cities: ["Grenville", "Tivoli", "Birchgrove"] },
      { name: "Saint David", cities: ["Woburn", "Calliste"] },
      { name: "Saint George", cities: ["Saint George's", "Grand Anse", "Belmont", "Tanteen"] },
      { name: "Saint John", cities: ["Gouyave", "Palmiste"] },
      { name: "Saint Mark", cities: ["Victoria"] },
      { name: "Saint Patrick", cities: ["Sauteurs", "Tivoli"] },
      { name: "Carriacou & Petite Martinique", cities: ["Hillsborough", "Harvey Vale", "L'Esterre"] },
    ],
  },
  {
    name: "Guadeloupe",
    state: [
      { name: "Basse-Terre", cities: ["Basse-Terre", "Gourbeyre", "Saint-Claude", "Capesterre-Belle-Eau", "Trois-Rivières", "Vieux-Habitants", "Bouillante", "Pointe-Noire"] },
      { name: "Grande-Terre", cities: ["Pointe-à-Pitre", "Les Abymes", "Le Gosier", "Sainte-Anne", "Saint-François", "Le Moule", "Baie-Mahault", "Morne-à-l'Eau"] },
      { name: "Marie-Galante", cities: ["Grand-Bourg", "Saint-Louis", "Capesterre-de-Marie-Galante"] },
      { name: "La Désirade", cities: ["Beauséjour"] },
      { name: "Les Saintes", cities: ["Terre-de-Haut", "Terre-de-Bas"] },
    ],
  },
  {
    name: "Martinique",
    state: [
      { name: "Centre", cities: ["Fort-de-France", "Le Lamentin", "Schoelcher", "Saint-Joseph"] },
      { name: "Nord", cities: ["Le Robert", "Sainte-Marie", "Gros-Morne", "La Trinité", "Basse-Pointe", "Macouba", "Le Lorrain", "Ajoupa-Bouillon", "Le Morne-Rouge"] },
      { name: "Sud", cities: ["Le Marin", "Sainte-Anne", "Le Vauclin", "Le François", "Le Saint-Esprit", "Rivière-Pilote", "Rivière-Salée", "Les Trois-Îlets", "Les Anses-d'Arlet", "Le Diamant"] },
      { name: "Ouest", cities: ["Case-Pilote", "Bellefontaine", "Le Carbet", "Saint-Pierre", "Le Prêcheur", "Fonds-Saint-Denis"] },
    ],
  },
  {
    name: "Montserrat",
    state: [
      { name: "Saint Anthony", cities: ["Brades", "Salem", "Davy Hill"] },
      { name: "Saint George", cities: ["Kinsale", "Plymouth"] },
      { name: "Saint Peter", cities: ["Saint John's", "Look Out"] },
    ],
  },
  {
    name: "Porto Rico",
    state: [
      { name: "Région Métropolitaine", cities: ["San Juan", "Bayamón", "Carolina", "Guaynabo", "Trujillo Alto", "Cataño"] },
      { name: "Région Nord", cities: ["Arecibo", "Barceloneta", "Camuy", "Manatí", "Hatillo"] },
      { name: "Région Ouest", cities: ["Mayagüez", "Aguadilla", "Isabela", "Cabo Rojo", "Aguada", "Rincón"] },
      { name: "Région Sud", cities: ["Ponce", "Coamo", "Salinas", "Yauco", "Guayama", "Juana Díaz"] },
      { name: "Région Est", cities: ["Humacao", "Caguas", "Fajardo", "Las Piedras", "Naguabo"] },
      { name: "Région Centre", cities: ["Adjuntas", "Jayuya", "Villalba", "Orocovis"] },
    ],
  },
  {
    name: "Saint-Barthélemy",
    state: [
      { name: "Main Island", cities: ["Gustavia", "Saint-Jean", "Lorient", "Grand Cul-de-Sac", "Flamands"] },
    ],
  },
  {
    name: "Saint-Kitts-et-Nevis",
    state: [
      { name: "Saint Kitts", cities: ["Basseterre", "Sandy Point Town", "Dieppe Bay Town", "Cayon", "Old Road Town"] },
      { name: "Nevis", cities: ["Charlestown", "Gingerland", "Newcastle", "Butlers", "Church Ground"] },
    ],
  },
  {
    name: "Sainte-Lucie",
    state: [
      { name: "Anse-la-Raye", cities: ["Anse-la-Raye"] },
      { name: "Canaries", cities: ["Canaries"] },
      { name: "Castries", cities: ["Castries", "Bisee", "Babonneau"] },
      { name: "Choiseul", cities: ["Choiseul", "Saltibus"] },
      { name: "Dennery", cities: ["Dennery", "Mon Repos"] },
      { name: "Gros Islet", cities: ["Gros Islet", "Rodney Bay", "Cap Estate"] },
      { name: "Laborie", cities: ["Laborie"] },
      { name: "Micoud", cities: ["Micoud", "Augier"] },
      { name: "Soufrière", cities: ["Soufrière", "Fond St. Jacques"] },
      { name: "Vieux Fort", cities: ["Vieux Fort", "Pierrot"] },
    ],
  },
  {
    name: "Saint-Martin",
    state: [
      { name: "Main Island", cities: ["Marigot", "Grand-Case", "Sandy Ground", "Cul-de-Sac", "Orient Bay", "Quartier d'Orléans"] },
    ],
  },
  {
    name: "Saint-Vincent-et-les-Grenadines",
    state: [
      { name: "Charlotte", cities: ["Georgetown", "Colonarie"] },
      { name: "Grenadines", cities: ["Bequia", "Union Island", "Canouan", "Mayreau"] },
      { name: "Saint Andrew", cities: ["Georgetown", "Sandy Bay"] },
      { name: "Saint David", cities: ["Chateaubelair", "Fitz Hughes"] },
      { name: "Saint George", cities: ["Kingstown", "Kingstown Park", "Arnos Vale"] },
      { name: "Saint Patrick", cities: ["Barrouallie", "Layou"] },
    ],
  },
  {
    name: "Sint Maarten",
    state: [
      { name: "Main Island", cities: ["Philipsburg", "Cole Bay", "Cul de Sac", "Lower Prince's Quarter", "Upper Prince's Quarter", "South Reward"] },
    ],
  },
  {
    name: "Suriname",
    state: [
      { name: "Brokopondo", cities: ["Brokopondo", "Brownsweg"] },
      { name: "Commewijne", cities: ["Nieuw Amsterdam", "Meerzorg"] },
      { name: "Coronie", cities: ["Totness"] },
      { name: "Marowijne", cities: ["Albina", "Moengo"] },
      { name: "Nickerie", cities: ["Nieuw Nickerie", "Wageningen", "Bigi Poika"] },
      { name: "Para", cities: ["Onverwacht", "Paramaribo-South"] },
      { name: "Paramaribo", cities: ["Paramaribo", "Zorg en Hoop", "Kwatta", "Latour", "Centrum"] },
      { name: "Saramacca", cities: ["Groningen", "Calcutta"] },
      { name: "Sipaliwini", cities: ["Bakhuis", "Apoera", "Tepoe"] },
      { name: "Wanica", cities: ["Lelydorp", "Domburg", "Henar", "Uitkijk"] },
    ],
  },
  {
    name: "Trinité-et-Tobago",
    state: [
      { name: "Arima", cities: ["Arima", "Cleaver Road", "O'Meara"] },
      { name: "Chaguanas", cities: ["Chaguanas", "Exchange", "Montrose"] },
      { name: "Couva-Tabaquite-Talparo", cities: ["Couva", "Tabaquite", "Talparo", "California", "Preysal"] },
      { name: "Diego Martin", cities: ["Diego Martin", "Petit Valley", "Carenage", "Cocorite"] },
      { name: "Mayaro-Rio Claro", cities: ["Mayaro", "Rio Claro", "Guayaguayare"] },
      { name: "Penal-Debe", cities: ["Penal", "Debe", "Barrackpore"] },
      { name: "Point Fortin", cities: ["Point Fortin", "Salazar Trace"] },
      { name: "Port of Spain", cities: ["Port of Spain", "St Clair", "Woodbrook", "Newtown", "Belmont"] },
      { name: "Princes Town", cities: ["Princes Town", "Barrackpore", "Mon Desir"] },
      { name: "San Fernando", cities: ["San Fernando", "Marabella", "Pleasantville", "Gasparillo"] },
      { name: "San Juan-Laventille", cities: ["San Juan", "Laventille", "Morvant", "Barataria"] },
      { name: "Sangre Grande", cities: ["Sangre Grande", "Manzanilla"] },
      { name: "Siparia", cities: ["Siparia", "Fyzabad", "Oropouche", "Palo Seco"] },
      { name: "Tobago", cities: ["Scarborough", "Plymouth", "Charlotteville", "Roxborough", "Canaan"] },
      { name: "Tunapuna-Piarco", cities: ["Tunapuna", "Piarco", "D'Abadie", "Trincity"] },
    ],
  },
  {
    name: "Îles Turques-et-Caïques",
    state: [
      { name: "Grand Turk", cities: ["Cockburn Town", "Back Salina", "Waterloo"] },
      { name: "South Caicos", cities: ["Cockburn Harbour"] },
      { name: "Providenciales", cities: ["Providenciales", "Blue Hills", "Five Cays"] },
      { name: "North Caicos", cities: ["Bottle Creek", "Kew", "Sandy Point"] },
      { name: "Middle Caicos", cities: ["Conch Bar", "Bambarra", "Lorimers"] },
      { name: "Salt Cay", cities: ["Balfour Town"] },
    ],
  },
  {
    name: "Îles Vierges américaines",
    state: [
      { name: "Saint Croix", cities: ["Christiansted", "Frederiksted", "Kingshill", "Sion Farm"] },
      { name: "Saint John", cities: ["Cruz Bay", "Coral Bay"] },
      { name: "Saint Thomas", cities: ["Charlotte Amalie", "Frenchtown", "Red Hook", "Crown Mountain"] },
    ],
  },
];

export default countries;
