export const PERMISSION_GROUPS: Record<string, string[]> = {
  organisation: [
    "organisation.view",
    "organisation.manage",
    "organisation.delete",
    "organisation.transfer_ownership",
  ],
  billing: ["billing.view", "billing.manage", "subscription.manage"],
  staff: ["staff.view", "staff.manage", "roles.manage"],
  events: [
    "events.view",
    "events.create",
    "events.edit",
    "events.delete",
    "events.publish",
    "event_days.manage",
    "sessions.manage",
  ],
  tickets: [
    "tickets.view",
    "tickets.manage",
    "tickets.refund",
    "tickets.cancel",
    "tickets.resend",
  ],
  attendees: ["attendees.view", "attendees.export"],
  finance: ["finance.view", "finance.export", "finance.payouts.view"],
  reports: ["reports.view", "reports.export"],
  other: [
    "memberships.manage",
    "reservations.manage",
    "checkin.perform",
    "scanner.use",
    "integrations.manage",
    "api_keys.manage",
    "webhooks.manage",
    "settings.manage",
    "branding.manage",
  ],
};

export const PERMISSION_LABELS: Record<string, string> = {
  "organisation.view": "View organisation",
  "organisation.manage": "Manage organisation",
  "organisation.delete": "Delete organisation",
  "organisation.transfer_ownership": "Transfer ownership",
  "billing.view": "View billing",
  "billing.manage": "Manage billing",
  "subscription.manage": "Manage subscription",
  "staff.view": "View staff",
  "staff.manage": "Manage staff",
  "roles.manage": "Manage roles",
  "events.view": "View events",
  "events.create": "Create events",
  "events.edit": "Edit events",
  "events.delete": "Delete events",
  "events.publish": "Publish events",
  "event_days.manage": "Manage event days",
  "sessions.manage": "Manage sessions",
  "tickets.view": "View tickets",
  "tickets.manage": "Manage tickets",
  "tickets.refund": "Refund tickets",
  "tickets.cancel": "Cancel tickets",
  "tickets.resend": "Resend tickets",
  "attendees.view": "View attendees",
  "attendees.export": "Export attendees",
  "finance.view": "View finance",
  "finance.export": "Export finance data",
  "finance.payouts.view": "View payouts",
  "reports.view": "View reports",
  "reports.export": "Export reports",
  "memberships.manage": "Manage memberships",
  "reservations.manage": "Manage reservations",
  "checkin.perform": "Perform check-in",
  "scanner.use": "Use scanner",
  "integrations.manage": "Manage integrations",
  "api_keys.manage": "Manage API keys",
  "webhooks.manage": "Manage webhooks",
  "settings.manage": "Manage settings",
  "branding.manage": "Manage branding",
};

// Role number → preset name (matches GetRoleName)
export const ROLE_NAMES: Record<number, string> = {
  1: "Staff",
  2: "FinanceManager",
  3: "EventManager",
  4: "Admin",
};

// Preset permission suggestions shown in the picker UI
export const PRESET_PERMISSIONS: Record<string, string[]> = {
  Staff: [
    "events.view",
    "tickets.view",
    "attendees.view",
    "checkin.perform",
    "scanner.use",
  ],
  FinanceManager: [
    "billing.view",
    "finance.view",
    "finance.export",
    "finance.payouts.view",
    "reports.view",
    "reports.export",
    "tickets.view",
    "tickets.refund",
    "tickets.cancel",
    "attendees.view",
  ],
  EventManager: [
    "staff.view",
    "events.view",
    "events.create",
    "events.edit",
    "events.publish",
    "event_days.manage",
    "sessions.manage",
    "tickets.view",
    "tickets.manage",
    "attendees.view",
    "attendees.export",
    "reports.view",
    "reservations.manage",
    "checkin.perform",
    "scanner.use",
  ],
  Admin: [
    "organisation.view",
    "staff.view",
    "staff.manage",
    // roles.manage stays Owner-only (mirrors the API and role defaults); it can
    // still be granted à la carte from the staff group if truly intended.
    "events.view",
    "events.create",
    "events.edit",
    "events.delete",
    "events.publish",
    "event_days.manage",
    "sessions.manage",
    "tickets.view",
    "tickets.manage",
    "tickets.refund",
    "tickets.cancel",
    "tickets.resend",
    "attendees.view",
    "attendees.export",
    "finance.view",
    "finance.export",
    "reports.view",
    "reports.export",
    "memberships.manage",
    "reservations.manage",
    "checkin.perform",
    "scanner.use",
    "integrations.manage",
    "settings.manage",
    "branding.manage",
  ],
};
