const countries = [
  {
    name: "Haiti",
    state: [
      {
        name: "Sud",
        cities: [
          "Les Cayes",
          "Aquin",
          "Cavaillon",
          "Saint-Louis-du-Sud",
          "Fond-des-Blancs",
          "Camp-Perrin",
          "Chantal",
          "Île-à-Vache",
          "Maniche",
          "Torbeck",
          "Chardonnières",
          "Les Anglais",
          "Tiburon",
          "Les Côteaux",
          "Port-à-Piment",
          "Roche-à-Bateaux",
          "Port-Salut",
          "Arniquet",
          "Saint-Jean-du-Sud",
        ],
      },
      {
        name: "Artibonite",
        cities: [
          "Dessalines",
          "Desdunes",
          "Grande-Saline",
          "Petite Rivière de l'Artibonite",
          "Gonaïves",
          "Ennery",
          "L'Estère",
          "Gros-Morne",
          "Anse-Rouge",
          "Terre-Neuve",
          "Marmelade",
          "Saint-Michel-de-l'Atalaye",
          "Saint-Marc",
          "Les Arcadins",
          "La Chapelle",
          "Liancourt",
          "Verrettes",
          "Montrouis",
        ],
      },
      {
        name: "Centre",
        cities: [
          "Cerca-la-Source",
          "Thomassique",
          "Hinche",
          "Cerca-Carvajal",
          "Maïssade",
          "Thomonde",
          "Lascahobas",
          "Baptiste",
          "Belladère",
          "Savanette",
          "Mirebalais",
          "Boucan-Carré",
          "Saut-d'Eau",
        ],
      },
      {
        name: "Grand'Anse",
        cities: [
          "Anse-d'Hainault",
          "Dame-Marie",
          "Les Irois",
          "Beaumont",
          "Corail",
          "Pestel",
          "Roseaux",
          "Jérémie",
          "Abricots",
          "Bonbon",
          "Chambellan",
          "Marfranc",
          "Moron",
        ],
      },
      {
        name: "Nippes",
        cities: [
          "Anse-à-Veau",
          "Arnaud",
          "L'Asile",
          "Petit-Trou-de-Nippes",
          "Plaisance-du-Sud",
          "Baradères",
          "Grand-Boucan",
          "Miragoâne",
          "Fonds-des-Nègres",
          "Paillant",
          "Petite-Rivière-de-Nippes",
        ],
      },
      {
        name: "Nord",
        cities: [
          "Acul-du-Nord",
          "Milot",
          "Plaine-du-Nord",
          "Borgne",
          "Port-Margot",
          "Cap-Haïtien",
          "Limonade",
          "Quartier-Morin",
          "Grande-Rivière-du-Nord",
          "Bahon",
          "Limbé",
          "Bas-Limbé",
          "Plaisance",
          "Pilate",
          "Saint-Raphaël",
          "Dondon",
          "La Victoire",
          "Pignon",
          "Ranquitte",
        ],
      },
      {
        name: "Nord-Est",
        cities: [
          "Fort-Liberté",
          "Perches",
          "Ferrier",
          "Ouanaminthe",
          "Capotille",
          "Mont-Organisé",
          "Trou-du-Nord",
          "Caracol",
          "Sainte-Suzanne",
          "Grand-Bassin",
          "Terrier-Rouge",
          "Vallières",
        ],
      },

      {
        name: "Nord-Ouest",
        cities: [
          "Môle-Saint-Nicolas",
          "Baie-de-Henne",
          "Bombardopolis",
          "Jean-Rabel",
          "Port-de-Paix",
          "Bassin-Bleu",
          "Chansolme",
          "Lapointe",
          "La Tortue",
          "Saint-Louis-du-Nord",
          "Anse-à-Foleur",
        ],
      },
      {
        name: "Ouest",
        cities: [
          "Arcahaie",
          "Cabaret",
          "Croix-des-Bouquets",
          "Cornillon",
          "Fonds-Verrettes",
          "Ganthier",
          "Thomazeau",
          "Anse-à-Galets",
          "Pointe-à-Raquette",
          "Léogâne",
          "Grand-Goâve",
          "Petit-Goâve",
          "Port-au-Prince",
          "Carrefour",
          "Cité Soleil",
          "Delmas",
          "Gressier",
          "Kenscoff",
          "Pétion-Ville",
          "Tabarre",
        ],
      },
      {
        name: "Sud-Est",
        cities: [
          "Bainet",
          "Côtes-de-Fer",
          "Belle-Anse",
          "Anse-à-Pitres",
          "Grand-Gosier",
          "Thiotte",
          "Jacmel",
          "Cayes-Jacmel",
          "La Vallée-de-Jacmel",
          "Marigot",
        ],
      },
    ],
  },
  {
    name: "United States",
    state: [
      {
        name: "Alabama",
        cities: [
          "Birmingham",
          "Montgomery",
          "Mobile",
          "Huntsville",
          "Tuscaloosa",
        ],
      },
      {
        name: "Alaska",
        cities: ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan"],
      },
      {
        name: "Arizona",
        cities: ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale"],
      },
      {
        name: "Arkansas",
        cities: [
          "Little Rock",
          "Fort Smith",
          "Fayetteville",
          "Springdale",
          "Jonesboro",
        ],
      },
      {
        name: "California",
        cities: [
          "Los Angeles",
          "San Diego",
          "San Jose",
          "San Francisco",
          "Sacramento",
          "Fresno",
          "Oakland",
        ],
      },
      {
        name: "Colorado",
        cities: [
          "Denver",
          "Colorado Springs",
          "Aurora",
          "Fort Collins",
          "Boulder",
        ],
      },
      {
        name: "Connecticut",
        cities: [
          "Bridgeport",
          "New Haven",
          "Hartford",
          "Stamford",
          "Waterbury",
        ],
      },
      {
        name: "Delaware",
        cities: ["Wilmington", "Dover", "Newark", "Middletown", "Smyrna"],
      },
      {
        name: "Florida",
        cities: [
          "Miami",
          "Orlando",
          "Tampa",
          "Jacksonville",
          "St. Petersburg",
          "Hialeah",
        ],
      },
      {
        name: "Georgia",
        cities: ["Atlanta", "Augusta", "Columbus", "Savannah", "Athens"],
      },
      {
        name: "Hawaii",
        cities: ["Honolulu", "Hilo", "Kailua", "Kapolei", "Kaneohe"],
      },
      {
        name: "Idaho",
        cities: ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello"],
      },
      {
        name: "Illinois",
        cities: [
          "Chicago",
          "Aurora",
          "Naperville",
          "Joliet",
          "Rockford",
          "Springfield",
        ],
      },
      {
        name: "Indiana",
        cities: [
          "Indianapolis",
          "Fort Wayne",
          "Evansville",
          "South Bend",
          "Carmel",
        ],
      },
      {
        name: "Iowa",
        cities: [
          "Des Moines",
          "Cedar Rapids",
          "Davenport",
          "Sioux City",
          "Iowa City",
        ],
      },
      {
        name: "Kansas",
        cities: ["Wichita", "Overland Park", "Kansas City", "Topeka", "Olathe"],
      },
      {
        name: "Kentucky",
        cities: [
          "Louisville",
          "Lexington",
          "Bowling Green",
          "Owensboro",
          "Covington",
        ],
      },
      {
        name: "Louisiana",
        cities: [
          "New Orleans",
          "Baton Rouge",
          "Shreveport",
          "Lafayette",
          "Lake Charles",
        ],
      },
      {
        name: "Maine",
        cities: ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn"],
      },
      {
        name: "Maryland",
        cities: [
          "Baltimore",
          "Frederick",
          "Rockville",
          "Gaithersburg",
          "Annapolis",
        ],
      },
      {
        name: "Massachusetts",
        cities: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"],
      },
      {
        name: "Michigan",
        cities: [
          "Detroit",
          "Grand Rapids",
          "Warren",
          "Sterling Heights",
          "Ann Arbor",
        ],
      },
      {
        name: "Minnesota",
        cities: [
          "Minneapolis",
          "Saint Paul",
          "Rochester",
          "Duluth",
          "Bloomington",
        ],
      },
      {
        name: "Mississippi",
        cities: ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi"],
      },
      {
        name: "Missouri",
        cities: [
          "Kansas City",
          "St. Louis",
          "Springfield",
          "Columbia",
          "Independence",
        ],
      },
      {
        name: "Montana",
        cities: ["Billings", "Missoula", "Great Falls", "Bozeman", "Helena"],
      },
      {
        name: "Nebraska",
        cities: ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
      },
      {
        name: "Nevada",
        cities: ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks"],
      },
      {
        name: "New Hampshire",
        cities: ["Manchester", "Nashua", "Concord", "Dover", "Rochester"],
      },
      {
        name: "New Jersey",
        cities: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Edison"],
      },
      {
        name: "New Mexico",
        cities: [
          "Albuquerque",
          "Las Cruces",
          "Rio Rancho",
          "Santa Fe",
          "Roswell",
        ],
      },
      {
        name: "New York",
        cities: [
          "New York City",
          "Buffalo",
          "Rochester",
          "Yonkers",
          "Syracuse",
          "Albany",
        ],
      },
      {
        name: "North Carolina",
        cities: [
          "Charlotte",
          "Raleigh",
          "Greensboro",
          "Durham",
          "Winston-Salem",
        ],
      },
      {
        name: "North Dakota",
        cities: ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"],
      },
      {
        name: "Ohio",
        cities: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron"],
      },
      {
        name: "Oklahoma",
        cities: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Lawton"],
      },
      {
        name: "Oregon",
        cities: ["Portland", "Salem", "Eugene", "Gresham", "Hillsboro"],
      },
      {
        name: "Pennsylvania",
        cities: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading"],
      },
      {
        name: "Rhode Island",
        cities: [
          "Providence",
          "Warwick",
          "Cranston",
          "Pawtucket",
          "East Providence",
        ],
      },
      {
        name: "South Carolina",
        cities: [
          "Charleston",
          "Columbia",
          "North Charleston",
          "Mount Pleasant",
          "Rock Hill",
        ],
      },
      {
        name: "South Dakota",
        cities: [
          "Sioux Falls",
          "Rapid City",
          "Aberdeen",
          "Brookings",
          "Watertown",
        ],
      },
      {
        name: "Tennessee",
        cities: [
          "Nashville",
          "Memphis",
          "Knoxville",
          "Chattanooga",
          "Clarksville",
        ],
      },
      {
        name: "Texas",
        cities: [
          "Houston",
          "San Antonio",
          "Dallas",
          "Austin",
          "Fort Worth",
          "El Paso",
        ],
      },
      {
        name: "Utah",
        cities: [
          "Salt Lake City",
          "West Valley City",
          "Provo",
          "West Jordan",
          "Orem",
        ],
      },
      {
        name: "Vermont",
        cities: [
          "Burlington",
          "South Burlington",
          "Rutland",
          "Barre",
          "Montpelier",
        ],
      },
      {
        name: "Virginia",
        cities: [
          "Virginia Beach",
          "Norfolk",
          "Chesapeake",
          "Richmond",
          "Arlington",
        ],
      },
      {
        name: "Washington",
        cities: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue"],
      },
      {
        name: "West Virginia",
        cities: [
          "Charleston",
          "Huntington",
          "Morgantown",
          "Parkersburg",
          "Wheeling",
        ],
      },
      {
        name: "Wisconsin",
        cities: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine"],
      },
      {
        name: "Wyoming",
        cities: ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"],
      },
      {
        name: "District of Columbia",
        cities: ["Washington"],
      },
    ],
  },
];

export default countries;
