const countries = [
  {
    name: "Haiti",
    state: [
      {
        name: "Sud",
        cities: [
          "Les Cayes",
          "Aquin",
          "Cavaillon",
          "Saint-Louis-du-Sud",
          "Fond-des-Blancs",
          "Camp-Perrin",
          "Chantal",
          "Île-à-Vache",
          "Maniche",
          "Torbeck",
          "Chardonnières",
          "Les Anglais",
          "Tiburon",
          "Les Côteaux",
          "Port-à-Piment",
          "Roche-à-Bateaux",
          "Port-Salut",
          "Arniquet",
          "Saint-Jean-du-Sud",
        ],
      },
      {
        name: "Artibonite",
        cities: [
          "Dessalines",
          "Desdunes",
          "Grande-Saline",
          "Petite Rivière de l'Artibonite",
          "Gonaïves",
          "Ennery",
          "L'Estère",
          "Gros-Morne",
          "Anse-Rouge",
          "Terre-Neuve",
          "Marmelade",
          "Saint-Michel-de-l'Atalaye",
          "Saint-Marc",
          "Les Arcadins",
          "La Chapelle",
          "Liancourt",
          "Verrettes",
          "Montrouis",
        ],
      },
      {
        name: "Centre",
        cities: [
          "Cerca-la-Source",
          "Thomassique",
          "Hinche",
          "Cerca-Carvajal",
          "Maïssade",
          "Thomonde",
          "Lascahobas",
          "Baptiste",
          "Belladère",
          "Savanette",
          "Mirebalais",
          "Boucan-Carré",
          "Saut-d'Eau",
        ],
      },
      {
        name: "Grand'Anse",
        cities: [
          "Anse-d'Hainault",
          "Dame-Marie",
          "Les Irois",
          "Beaumont",
          "Corail",
          "Pestel",
          "Roseaux",
          "Jérémie",
          "Abricots",
          "Bonbon",
          "Chambellan",
          "Marfranc",
          "Moron",
        ],
      },
      {
        name: "Nippes",
        cities: [
          "Anse-à-Veau",
          "Arnaud",
          "L'Asile",
          "Petit-Trou-de-Nippes",
          "Plaisance-du-Sud",
          "Baradères",
          "Grand-Boucan",
          "Miragoâne",
          "Fonds-des-Nègres",
          "Paillant",
          "Petite-Rivière-de-Nippes",
        ],
      },
      {
        name: "Nord",
        cities: [
          "Acul-du-Nord",
          "Milot",
          "Plaine-du-Nord",
          "Borgne",
          "Port-Margot",
          "Cap-Haïtien",
          "Limonade",
          "Quartier-Morin",
          "Grande-Rivière-du-Nord",
          "Bahon",
          "Limbé",
          "Bas-Limbé",
          "Plaisance",
          "Pilate",
          "Saint-Raphaël",
          "Dondon",
          "La Victoire",
          "Pignon",
          "Ranquitte",
        ],
      },
      {
        name: "Nord-Est",
        cities: [
          "Fort-Liberté",
          "Perches",
          "Ferrier",
          "Ouanaminthe",
          "Capotille",
          "Mont-Organisé",
          "Trou-du-Nord",
          "Caracol",
          "Sainte-Suzanne",
          "Grand-Bassin",
          "Terrier-Rouge",
          "Vallières",
        ],
      },

      {
        name: "Nord-Ouest",
        cities: [
          "Môle-Saint-Nicolas",
          "Baie-de-Henne",
          "Bombardopolis",
          "Jean-Rabel",
          "Port-de-Paix",
          "Bassin-Bleu",
          "Chansolme",
          "Lapointe",
          "La Tortue",
          "Saint-Louis-du-Nord",
          "Anse-à-Foleur",
        ],
      },
      {
        name: "Ouest",
        cities: [
          "Arcahaie",
          "Cabaret",
          "Croix-des-Bouquets",
          "Cornillon",
          "Fonds-Verrettes",
          "Ganthier",
          "Thomazeau",
          "Anse-à-Galets",
          "Pointe-à-Raquette",
          "Léogâne",
          "Grand-Goâve",
          "Petit-Goâve",
          "Port-au-Prince",
          "Carrefour",
          "Cité Soleil",
          "Delmas",
          "Gressier",
          "Kenscoff",
          "Pétion-Ville",
          "Tabarre",
        ],
      },
      {
        name: "Sud-Est",
        cities: [
          "Bainet",
          "Côtes-de-Fer",
          "Belle-Anse",
          "Anse-à-Pitres",
          "Grand-Gosier",
          "Thiotte",
          "Jacmel",
          "Cayes-Jacmel",
          "La Vallée-de-Jacmel",
          "Marigot",
        ],
      },
    ],
  },
];

export default countries;
